// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import IsbnConvertController from "./isbn_convert_controller"
application.register("isbn-convert", IsbnConvertController)

import IsbnSearchController from "./isbn_search_controller"
application.register("isbn-search", IsbnSearchController)
